// Copyright 2014 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.


// This file is autogenerated by
//     base/android/jni_generator/jni_generator.py
// For
//     org/chromium/android_webview/gfx/AwDrawFnImpl

//#ifndef org_chromium_android_webview_gfx_AwDrawFnImpl_JNI
//#define org_chromium_android_webview_gfx_AwDrawFnImpl_JNI

#include <jni.h>
#include "aw_draw_fn_impl.h"
#include "DrawGLFunctor.h"

//#include "../../../../../base/android/jni_generator/jni_generator_helper.h"


// Step 1: Forward declarations.


// Step 2: Constants (optional).


// Step 3: Method stubs.
namespace android_webview {

static jint GetFunctorHandle(
    JNIEnv* env,
    jclass jcaller,
    jlong nativeAwDrawFnImpl) {
    android_webview::AwDrawFnImpl* native = reinterpret_cast<android_webview::AwDrawFnImpl*>(nativeAwDrawFnImpl);
  return native->GetFunctorHandle(env);
}

static void ReleaseHandle(
    JNIEnv* env,
    jclass jcaller,
    jlong nativeAwDrawFnImpl) {
    android_webview::AwDrawFnImpl* native = reinterpret_cast<android_webview::AwDrawFnImpl*>(nativeAwDrawFnImpl);
  return native->ReleaseHandle(env);
}

void JNI_AwDrawFnImpl_SetDrawFnFunctionTable(JNIEnv* env, jlong functionTablePointer);

static void SetDrawFnFunctionTable(
    JNIEnv* env,
    jclass jcaller,
    jlong functionTablePointer) {
  return JNI_AwDrawFnImpl_SetDrawFnFunctionTable(env, functionTablePointer);
}


static jlong Create(
    JNIEnv* env,
    jclass jcaller,
    jobject caller) {
    return reinterpret_cast<intptr_t>(new android_webview::AwDrawFnImpl(new android::JNIFunctorContext(env, jcaller, caller)));
}


}  // namespace android_webview

//#endif  // org_chromium_android_webview_gfx_AwDrawFnImpl_JNI
